### ISSUE TITLE
Heartbeat getting sent during inactivity

### ISSUE THREAD

**Issue by zanthous** [danexrc/Crackboard-VS#1]
I left visual studio on overnight and it submitted activity for the entire duration for some reason
![image](https://github.com/user-attachments/assets/2669b687-6587-4a6f-96a0-3d9baa53cd7d)

I've disabled it now

**Comment by danewrx** [comment]
This should be fixed in v1.2. You can install here:

[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=danexrc.crackboard-vs)
[GitHub Releases](https://github.com/danexrc/Crackboard-VS/releases/tag/1.2)

Please give it a try and let me know if you experience any further issues.

**Comment by zanthous** [comment]
> This should be fixed in v1.2. You can install here:
> 
> [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=danexrc.crackboard-vs) [GitHub Releases](https://github.com/danexrc/Crackboard-VS/releases/tag/1.2)
> 
> Please give it a try and let me know if you experience any further issues.

Thanks! I'll try it out tonight:

Edit: after a couple days, everything seems to be working correctly 👍
